### ISSUE TITLE
关于配置文件的一些疑惑

### ISSUE THREAD

**Issue by loyess** [breakwa2333/Crack#1]
1. Server和Client配置文件中crt、key、ca这三个字段是自签的证书吗？能否提供下自签的方法，谢谢！
2. Client配置文件中china_list_path字段，这里的白名单文件是json格式，里面的类容样式是什么样的？
3. Client配置文件中active字段作用是？怎么填写？
4. LocalServer.py文件中配置文件获取有些问题 [L17-L22](https://github.com/breakwa2333/Crack/blob/2c3f7bd97104b4702610c08d5ce8efbcbc2d9f10/LocalServer.py#L17-L22)

**Comment by breakwa2333** [comment]
1、目前暂时只能使用自签证书，以后版本会加入CA机构证书的支持。如何自签可以上网搜一下，这里还没有写详细的教程，但是有一个fakeCA的项目可以帮助完成大部分工作。
2、chinalist模板现在已经上传到仓库了，基本功能已经实现，查询平均用时不到2μs
3、active字段给你一个示例，如下图（信息是假的）
![批注 2020-01-05 172218](https://user-images.githubusercontent.com/48397771/71777790-087fe280-2fe0-11ea-80f7-517cf7bceaa8.png)

**Comment by breakwa2333** [comment]
配置文件获取的话，不是很清楚你那边问题在哪里。估计可能和Python路径有关系，Windows下路径“\”会被认为是转义符。这个可能要等到再下一次更新的时候解决了，会在这几天内解决的。

**Comment by breakwa2333** [comment]
问题理论上修复了，配置文件的详细介绍在[PROFILE](https://github.com/breakwa2333/Crack#profile-keywords-%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6%E5%85%B3%E9%94%AE%E5%AD%97)

**Comment by loyess** [comment]
首先，感谢你耐心的回复！

`openssl req -new -x509 -days 365 -nodes -out server.crt -keyout server.key`

我用上面的代码生成的自签证书，server 和 client 端的 crt、key、ca字段如下：
```
crt：server.crt
key：server.key

ca：server.crt   # 同server端的 crt 字段路径下的文件内容相同
```

本地client 端 local_port 字段为 1080 ， 软件中设置 socks5 代理为 127.0.0.1:1080， 不能连接。


请问我自签证书后的配置是否有问题？还有软件中使用代理的方式是否正确？是用socks5代理吗？

**Comment by breakwa2333** [comment]
感谢支持。
1、这个代理目前只是HTTP代理，以后会增加socks5代理。这个HTTP代理对Telegram的支持现在发现有一些问题（Telegram断流），在后续版本中会做出相应改进。
2、这个配置确实有问题。localserver的ca文件内容应是根证书，而不是使用根证书签发的服务器证书。

**Comment by public15** [comment]
localserver的ca文件内容应是根证书?在安卓手机上用termux运行，未提示错误，但连不上。我是留空的，如下：
{
    "mode": "auto",
    "active": "test",
    "test": {
        "uuid": "422a1234-1234-2234-1234-7a11bc121234",
        "ca": "",
        "server_host": "xxx.com",
        "server_port": "8443",
        "local_port": "8443",
        "china_list_path": "./chinalist.txt"
    }
}

**Comment by breakwa2333** [comment]
对的，就是自签所用的根证书，如果不是自签的话填default，留空在目前版本中是不行的，以后会加上去。不报错是因为已经将错误捕获了，在后续版本中将会加入错误日志。
![批注 2020-01-08 075051](https://user-images.githubusercontent.com/48397771/71938825-a0055100-31eb-11ea-8de6-dc0e44f3b6bb.png)

**Comment by public15** [comment]
服务器端如下，查看端口8443也在监听状态,无法连接成功
{
    "uuids": [
        "422a1234-1234-2234-1234-7a11bc121234"
    ],
    "crt": "/root/ca/XX.pem",
    "key": "/root/ca/XX.key",
    "port": "8443"
}
客户端
{
"mode": "auto",
"active": "test",
"test": {
"uuid": "422a1234-1234-2234-1234-7a11bc121234",
"ca": "default",
"server_host": "xxx.com",
"server_port": "8443",
"local_port": "8443",
"china_list_path": "./chinalist.txt"
}
}

**Comment by breakwa2333** [comment]
感谢支持！
代理实际测试过没有问题再发布的。目测可能还是证书的问题，如果是自签证书请确认是否签发正确，不是的话确认是否可以给该网址使用。等今天把错误日志加上去应该就知道问题出哪里了。

**Comment by public15** [comment]
非自签证书，域名正确，可能是我哪里没有操作对，后续加上日志再试，感谢开发

**Comment by loyess** [comment]
请问你用你的这个项目 [FakeCA](https://github.com/breakwa2333/FakeCA)签发的证书，用在此项目有成功过吗？

**Comment by loyess** [comment]
用chrome的代理管理插件SwitchyOmega的http代理连接到本地客户端端口时，服务器端报错如下：
```
Exception happened during processing of request from ('16.26.36.46', 4234)Traceback (most recent call last):
  File "Server.py", line 18, in handle
    self.load_TLS()
  File "Server.py", line 55, in load_TLS
    context.minimum_version = TLSVersion.TLSv1_3
  File "/usr/local/python3.7/lib/python3.7/ssl.py", line 502, in minimum_version
    super(SSLContext, SSLContext).minimum_version.__set__(self, value)
ValueError: Unsupported protocol version 0x304

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3.7/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/python3.7/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/python3.7/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "Server.py", line 23, in handle
    self.client.close()
AttributeError: 'TCP_handler' object has no attribute 'client'
```

整个过程代理网络是无法联通的

**Comment by public15** [comment]
> 请问你用你的这个项目 [FakeCA](https://github.com/breakwa2333/FakeCA)签发的证书，用在此项目有成功过吗？



> 请问你用你的这个项目 [FakeCA](https://github.com/breakwa2333/FakeCA)签发的证书，用在此项目有成功过吗？

用的阿里～DV免费个人证书

**Comment by breakwa2333** [comment]
> 请问你用你的这个项目 [FakeCA](https://github.com/breakwa2333/FakeCA)签发的证书，用在此项目有成功过吗？

测试一直使用这个半自动脚本，注意company name一定要一致，common name无所谓，默认在使用者可选名中添加本机所获取到的IP地址。
![批注 2020-01-08 214936](https://user-images.githubusercontent.com/48397771/71983278-62430f80-3261-11ea-93dc-e7a7e1c86701.png)

**Comment by breakwa2333** [comment]
> 用chrome的代理管理插件SwitchyOmega的http代理连接到本地客户端端口时，服务器端报错如下：
> 
> ```
> Exception happened during processing of request from ('16.26.36.46', 4234)Traceback (most recent call last):
>   File "Server.py", line 18, in handle
>     self.load_TLS()
>   File "Server.py", line 55, in load_TLS
>     context.minimum_version = TLSVersion.TLSv1_3
>   File "/usr/local/python3.7/lib/python3.7/ssl.py", line 502, in minimum_version
>     super(SSLContext, SSLContext).minimum_version.__set__(self, value)
> ValueError: Unsupported protocol version 0x304
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/python3.7/lib/python3.7/socketserver.py", line 650, in process_request_thread
>     self.finish_request(request, client_address)
>   File "/usr/local/python3.7/lib/python3.7/socketserver.py", line 360, in finish_request
>     self.RequestHandlerClass(request, client_address, self)
>   File "/usr/local/python3.7/lib/python3.7/socketserver.py", line 720, in __init__
>     self.handle()
>   File "Server.py", line 23, in handle
>     self.client.close()
> AttributeError: 'TCP_handler' object has no attribute 'client'
> ```
> 
> 整个过程代理网络是无法联通的

这个是因为你openssl版本太老了，至少要1.1.1。对应的就是python3.7.4以上，推荐3.7.6。服务器如果版本低会这样，你本地版本低也会这样，不过这里看起来更像是你本地的问题。

**Comment by public15** [comment]
已测试成功😀

**Comment by breakwa2333** [comment]
> 已测试成功😀

所以到底是什么原因？

**Comment by public15** [comment]
重新签发一个DV证书，在手机上试的，暂未知原因，抽空再看下

**Comment by breakwa2333** [comment]
> 重新签发一个DV证书，在手机上试的，暂未知原因，抽空再看下

OK，谢谢！

**Comment by public15** [comment]
由于 Telegram 是直接使用 IP 进行通讯，所以 http 代理对于 Telegram 并没有什么作用，何时同时支持socks5让 Telegram 能够走代理呢，毕竟手机耗电是个问题，这样可以crack+APN（wifi下http代理）

**Comment by public15** [comment]
> 
> 
> 由于 Telegram 是直接使用 IP 进行通讯，所以 http 代理对于 Telegram 并没有什么作用，何时同时支持socks5让 Telegram 能够走代理呢，毕竟手机耗电是个问题，这样可以crack+APN（wifi下http代理）
暂时用gost将http转成socks5
nohup ./gost -L=:8444 -F=127.0.0.1:8443&

**Comment by breakwa2333** [comment]
> 由于 Telegram 是直接使用 IP 进行通讯，所以 http 代理对于 Telegram 并没有什么作用，何时同时支持socks5让 Telegram 能够走代理呢，毕竟手机耗电是个问题，这样可以crack+APN（wifi下http代理）

这个需要一些时间，最快的话下周之前吧。计划是先把日志做掉，然后把socks5做掉。理论上socks5代理和HTTP可以共用一个端口，自动识别，所以打算朝这个方向做。

**Comment by public15** [comment]
好的谢谢，后续有没有意向加上GEOIP

**Comment by breakwa2333** [comment]
> 由于 Telegram 是直接使用 IP 进行通讯，所以 http 代理对于 Telegram 并没有什么作用，何时同时支持socks5让 Telegram 能够走代理呢，毕竟手机耗电是个问题，这样可以crack+APN（wifi下http代理）

Telegram问题找到了，loop函数里面没有修改请求头。现在加上去就解决了，不过性能有很大问题，python毕竟还是python，说来也巧是在调试GEOIP时候发现的。用代理路由管理页面死活访问不了，然后抓包就发现了这个问题。

**Comment by public15** [comment]
1.0.6中SOCKS5代理似乎未生效，telegram还是不行,是不是要单独配置

**Comment by breakwa2333** [comment]
> 1.0.6中SOCKS5代理似乎未生效，telegram还是不行,是不是要单独配置

没有要单独配置的，Windows下测试是成功的，其他平台不清楚我现在去测试一下。

**Comment by public15** [comment]
Android10

**Comment by breakwa2333** [comment]
> Android10

找到问题了，是有BUG。这不是Crack的锅，Crack的SOCKS5完全遵从RFC1928,RFC1929标准，xshell和桌面版telegram一点问题也没有，就是移动版有这种问题。
![批注 2020-01-12 173446](https://user-images.githubusercontent.com/48397771/72216886-eba85980-3561-11ea-997e-eb927207133c.png)

**Comment by breakwa2333** [comment]
这个问题有点严重，应该是telegram修改了内部代码，然后IOS和Android就无法使用socks5代理了。计划是Crack内部加入MTProxy解决这个问题。

**Comment by public15** [comment]
MTProxy很容易被墙哦

**Comment by public15** [comment]
geoip_path填写geoip.txt,实际测试并未生效

**Comment by breakwa2333** [comment]
> geoip_path填写geoip.txt,实际测试并未生效

对的，还没有完全做好，这只是一个本地的demo，写完之后要放在server端运行的。其实geoip这个东西如果要快的话会导致DNS泄漏，比如本地请求DNS然后匹配验证，所以只能权衡一下。计划是这样的，如果一个域名不在Chinalist列表中就直接请求代理服务器，如果代理服务器获取的DNS为中国IP就在返回的数据头部添加标记并关闭连接，客户端收到标记后重新请求DNS并直接访问服务器。这样会增加至少1-RTT的延迟（不计TLS握手）。

**Comment by breakwa2333** [comment]
> MTProxy很容易被墙哦

Crack会给他建立TLS隧道，理论上会好很多，实际上不清楚有待测试。然后关于还有计划对Crack的LocalServer增加L2TP协议的支持，这样即使移动设备Telegram不设置代理也可以访问。

**Comment by breakwa2333** [comment]
现在还有一个问题是Crack对IPv6支持不完全，IPv6本身不复杂但是因为IPv4和IPv6在很长一段时期是会同时存在的，所以要处理一些IPv4 to IPv6隧道或者IPv6 to IPv4隧道，有个比较常见的例子就是微信表情包服务器就是这种类型。
